name: Build Extension in different branch

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Create or update branch with dist files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Check if the branch already exists
          if git show-ref --verify --quiet refs/heads/build-extension-branch; then
            git checkout build-extension-branch
          else
            git checkout -b build-extension-branch
          fi

          # Clear the existing dist files in the branch
          rm -rf dist/*

          # Copy built files to the dist directory
          cp -r dist/* dist/
          git add dist/*
          git commit -m "Update built extension artifacts" || echo "No changes to commit"

      - name: Push to new branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin build-extension-branch --force
